#!/bin/bash
#!/usr/bin/env bash

files_to_lint=$(git diff --cached --name-only --diff-filter=ACM |  grep "(\.js|\.vue)$" -E)

if [ -n "$files_to_lint" ]; then
    ./node_modules/.bin/eslint --quiet $files_to_lint
fi