# This configuration was used Ebert to review the kf8a/drought repository
# on ed48ed394f3819c94f27a2ab208acaf194ad8161.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to https://ebertapp.io/docs/config and see the configuration
# details.
---
styleguide: plataformatec/linters
engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
- config
- priv/repo
- test
- web/static/css/app.css
- web/static/css/phoenix.css
- web/static/js/app.js